sudo: false
language: php
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.composer/cache
notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
  - name: Test with PHP Nightly
  include:

  - name: Test with PHP 5.3
    dist: precise
    php: '5.3'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 5.4
    dist: trusty
    php: '5.4'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 5.5
    dist: trusty
    php: '5.5'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 5.6
    php: '5.6'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 7.0
    php: '7.0'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 7.1 (with code coverage)
    php: '7.1'
    before_script:
    - curl --location --output ocular.phar --retry 3 --silent --show-error https://scrutinizer-ci.com/ocular.phar
    - composer --no-interaction require --dev --no-suggest --no-update 'php-coveralls/php-coveralls:^2.0'
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test -- --coverage-clover coverage-clover.xml
    after_script:
    - ./vendor/bin/php-coveralls --no-interaction --coverage_clover=coverage-clover.xml --json_path=coveralls-upload.json
    - php ocular.phar code-coverage:upload --format=php-clover coverage-clover.xml

  - name: Test with PHP 7.2
    php: '7.2'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 7.3
    php: '7.3'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP 7.4
    php: '7.4'
    before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test

  - name: Test with PHP Nightly
    php: nightly
    before_script:
    - phpenv config-rm xdebug.ini || true
    - composer --no-interaction config platform.php 7.4.0
    - travis_retry composer --no-interaction install
    script:
    - composer --no-interaction run-script test
